name: Upload Artifact Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if sources.m3u exists
      run: |
        if [ ! -f ./sources.m3u ]; then
          echo "sources.m3u not found!"
          exit 1
        else
          echo "sources.m3u found!"
        fi

    - name: Upload result artifact
      uses: actions/upload-artifact@v1
      with:
        name: sources
        path: ./sources.m3u
