name: Simple Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./sources.m3u
