name: Run Python Script

on:
  push:
    branches:
      - main  # Изпълнява се при push към main

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Работи на последната версия на Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Вземаме репозиторието

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Изберете версия на Python, която искате

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ако имате зависимостите в requirements.txt

      - name: Run Python Script
        run: |
          python newchange_engine.py  # Скриптът е в директория "scripts"
          
      - name: Set environment variables
        run: |
          echo "source_repo_path=source_repo" >> $GITHUB_ENV
          echo "destination_repo_path=destination" >> $GITHUB_ENV  # Задаваме пътищата

      - name: Run the Python script with paths
        run: |
          python newchange_engine.py  # Можеш да предадеш тези пътища като параметри към скрипта
