

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout на кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Конфигурирай Git с потребителско име и имейл
      - name: Set git user
        run: |
          git config --global user.email "belchew@outlook.com"
          git config --global user.name "belchew"

      # Извлечи последните промени от отдалеченото хранилище
      - name: Pull latest changes from origin/main
        run: |
          git fetch origin
          git pull origin main

      # Направи промените, които искаш (например, замени съдържание на файл)
      - name: Modify file
        run: |
          # Вашият скрипт за модификация на файла

      # Добави промените към git и извърши commit
      - name: Commit changes
        run: |
          git add .
          git commit -m "Modified basic.m3u"
          
      # Push промените обратно в отдалеченото хранилище
      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
